GET http://localhost:3000/customer

###

POST http://localhost:3000/customer
Content-Type: application/json

{
	"name": "sam",
	"email": "sam@test.com",
	"password": "secret",
	"phonenumber": "6474782",
	"address": "46 main st"
}

###

PUT http://localhost:3000/customer
Content-Type: application/json

{
	"ID": "dc7742db-470d-4970-905c-e536713276bc",
	"name": "vicky",
	"email": "vicky@test.com",
	"password": "secret",
	"phonenumber": "6474782",
	"address": "46 main st"
}

###

DELETE http://localhost:3000/customer
Content-Type: application/json

{
	"ID": "dc7742db-470d-4970-905c-e536713276bc"
}